### ISSUE TITLE
Why `f64`?

### ISSUE THREAD

**Issue by ctrlcctrlv** [linebender/norad#108]
This is in some ways a follow up to #107, but is also different.

`glifparser` uses `f32` to represent its point data. Specifically, it converts UFO glif's to a representation which is like this simplified one: 

```rust
type Outline = Vec<Contour>;
type Contour = Vec<Point>;

struct Point {
  x: f32,
  y: f32,
  a: Handle,
  b: Handle
}

enum Handle {
  At(f32, f32),
  Colocated
}
```

I was wondering why Norad uses `f64`. I think this is perhaps overly optimistic. TTF fonts, of course, always round to int. But it's my understanding that the PostScript CFF format is also `f32`. Per [here](https://www.tinaja.com/glib/ps8dprp1.pdf), [here](https://www-cdf.fnal.gov/offline/PostScript/PLRM3.pdf). So, I think, the maximum precision of a point must be `f32`. Anyway, I'm uneasy about what people's rasterizers etc would do to my fonts, so consider `f32` the max available precision. 

You can say, "well, UFO could compile to some as yet unknown font format which will be f64", but I don't think it's very clear that future font formats would even be f64. It's a big increase in filesize for no benefit, due to UPM in the thousands in most high quality fonts.

It also leads to smaller files to use `f32`, as you get some free rounding.

This is obviously a major incompatibility, so I guess one of us needs to convince the other on this issue. I can be convinced, if the argument is good.

**Comment by madig** [comment]
Huh? I commonly encounter f32. https://github.com/linebender/norad/blob/master/src/glyph/mod.rs#L258-L259

**Comment by cmyr** [comment]
In *kurbo* we decided to always use f64 because we didn't want to be generic over the float type, and we were more concerned about precision and representing large values than we were about smaller binary size.

In norad, we do generally use `f32`, though? See [`Glyph`](https://github.com/linebender/norad/blob/master/src/glyph/mod.rs#L31), [`ContourPoint`](https://github.com/linebender/norad/blob/master/src/glyph/mod.rs#L258). The only place where we do use f64 is in some of the values in `fontinfo.plist`.

**Comment by ctrlcctrlv** [comment]
Right, sorry, wrong repo :-)
