### ISSUE TITLE
Stricter names for things

### ISSUE THREAD

**Issue by madig** [linebender/norad#191]
The spec contains wording like 

> The name of the glyph. This must be at least one character long. Names must not contain control characters. 

in various places, specifically for glyph, layer and group names (which therefore also extends to the contents of kerning.plist).

Maybe this can be enforce with a newtype `struct Name(String)` that implements a constructor that ensures the string has > 0 characters and contains no control characters.

This type would supersede `GlyphName` and `LayerName` or at least the `str` inside them.

**Comment by cmyr** [comment]
Okay I like this, since it provides a way to abstract out the concrete type of a glyph name, I'll implement this now.

**Comment by cmyr** [comment]
Okay, so i've dug into this a bit and there are a some decisions to make.

Because names now need to be validated, we need to decide what to do with API that take names, like `Glyph::new_named` or `Layer::get`. Currently these just take `&str`. I can see at least three possible options:

- make these methods fallible, and return an `Error` if the name is malformed.
- make these methods take a `Name`, and require the caller to construct a `Name` struct before calling
- allow these methods to take a `&str`, with the invariant that it is a valid identifer; panic if it is not.

There are maybe others, like taking `&str` and replacing invalid contents, but I think that is worse than any of these three options.

In practice, all of these feel bad in different ways. The first two feel bad because they make the API harder to use for a very unusual case. The characters that are disallowed in glyph names are all characters that you cannot type with a keyboard; constructing an invalid name would require specific effort on the part of the caller, so in practice I would expect the user to just `unwrap` everwhere. An API where you always `unwrap` is not helpful. The only case that could arise naturally would be when the user passes the empty string.

It's also possible that we could mix and match these approaches somewhat. Methods that already return an error could return an error in the bad-name case without it being any additional headache for the user, for instance.

In other cases, my preference is probably for number 3, where we panic explicitly. I think that since the user is going to unwrap in the case of the other designs (and so panic anyway) having us panic in a way that is clearly documented lets us keep the API useable.

I'll think about this a bit more, but wanted to write down my thoughts.

**Comment by madig** [comment]
Option 3 sounds good. Not ideal, but eh. Another option would be to not deal with this at a type level and instead check it at load/save time. I would prefer a type-level solution though...
